apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: allenwu1/config-server:latest
          ports:
            - containerPort: 8888
          resources:
            requests:
              memory: "128Mi"
            limits:
              memory: "256Mi"