apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: config-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: config-server-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50